name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PYTHON_VERSION: "3.11"

jobs:
  client-app:
    name: Client App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client-app
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Poetry
      run: pipx install poetry

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ./client-app/.venv
          ~/.cache/pypoetry
        key: client-app-${{ hashFiles('client-app/poetry.lock') }}

    - name: Install dependencies
      run: poetry install --no-root

    - name: Lint with Ruff
      run: poetry run ruff check .

    - name: Run tests
      run: poetry run pytest -v